---
- hosts: all
  tasks:
      - name: check local time
        command: date
        register: command_result
        changed_when: true

      - name: print local time
        debug:
            var: command_result.stdout
