---
- name: Working with roles
  hosts: servers
  become: yes
  vars:
    ssh_port: 2022
    allow_users: ansible, root
    permit_root: yes

  tasks:
    - name: ensure SELinux is in enforcing mode
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=enforcing

    - name: enable new sshd firewall
      firewalld:
        port: 2022/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: install policycoreutils for rhel8
      yum:
        name: policycoreutils-python-utils.noarch
        state: present

    - name: ensure the appropriate SELinux context is set on new sshd port
      seport:
        ports: 2022
        proto: tcp
        setype: ssh_port_t
        state: present

    - name: called task6 role only when OS family is set to RedHat
      include_role:
        name: task6-role
      when: ansible_facts['os_family'] == 'RedHat'
