---
- name: Repository configuration
  hosts: dbservers
  tasks:
    - name: Ensure Example Repo exists
      yum_repository:
        name: example-internal
        description: Example Inc. Internal YUM repo
        file: example
        baseur: http://materials.example.com/yum/repository/
        gpgcheck: yes

    - name: Ensure Repo RMP Key is Installed
      rpm_key:
        key: http://materials.example.com/yum/repository/RPM-GPG-KEY-example
        state: present

    - name: Install Example motd package
      yum:
        name: example-motd
        state: present
