---
- name: Create multiple local users
  hosts: webservers
  become: true
  vars_files:
    - vars/users_vars.yml
  tasks:
    - name: Add webadmins group
      group:
        name: webadmins
        state: present

    - name: Create user accounts
      user:
        name: "{{ item.username }}"
        state: present
        groups: "{{ item.groups }}"
      loop: "{{ users }}"
