---
- name: Implementing Handlers
  hosts: all
  become: true
  tasks:
    - name: copy demo.example.conf configuration template
      template:
        src: /var/lib/templates/demo.example.conf.template
        dest: /etc/httpd/conf.d/demo.example.conf
      notify:
        - restart mysql
        - restart apache

  handlers:
    - name: restart mysql
      service:
        name: mariadb
        state: restarted

    - name: restart apache
      service:
        name: httpd
        state: restarted
