---
- name: show selinux
  hosts: all
  tasks:
      - name: install required packages
        yum:
            name: policycoreutils-python-utils
            state: present

      - name: set selinux context
        community.general.sefcontext:
            target: /tmp/removeme
            setype: tmp_t
            state: present
        notify:
            - run restorecon

  handlers:
      - name: run restorecon
        command: restorecon -v /tmp/removeme
