---
- name: Ignoring Task Failure
  hosts: all
  become: true
  tasks:
    - name: Latest version of notapkg is installed
      yum:
        name: notapkg
        state: latest
      ignore_errors: yes
