---
- name: lab - implementing tasks
  hosts: all
  vars_files:
      - vars/main.yml
  tasks:
      - name: install mariadb-server package
        yum:
            name: mariadb-server.x86_64
            state: present
        when: ansible_distribution_major_version == "8"

      - name: ensure mariadb server is started and enabled
        service:
            name: mariadb
            state: started
            enabled: yes
        notify: root-pass

      - name: install python-PyMySQL client
        yum:
            name: python3-PyMySQL.noarch
            state: present
        when: ansible_distribution_major_version == "8"
        
  handlers:
      - name: root-pass
        mysql_user:
            name: root
            password: "{{ root_password }}"
            state: present
