---
- name: using multiple conditions
  hosts: all
  tasks:
    - name: install httpd package
      package:
        name: httpd
        state: installed
      when:
        - ansible_distribution == "RedHat"
        - ansible_memfree_mb > 512
