---
- name: create users using a loop
  hosts: all
  tasks:
    - name: create users
      user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - name: lco_admin
          groups: wheel
        - name: lco_backup
          groups: users
        - name: lco_restore
          groups: users
