---
- name: Recurring cron job
  hosts: all
  become: true
  tasks:
      - name: Crontab file exists
        cron:
            name: Add date and time to a file
            minute: "*/2"
            hour: 9-16
            weekday: 1-5
            user: lupera1
            job: /usr/bin/date >> /home/lupera1/my_date_time_cron_job
            cron_file: add-date-time
            state: present

