---
- name: Remove scheduled cron job
  hosts: all
  become: true
  tasks:
      - name: Cron job removed
        cron:
            name: Add date and time to a file
            user: lupera1
            cron_file: add-date-time
            state: absent
