---
- name: create user ansible
  hosts: all
  become: yes
  vars_files:
    - ../vars/pass.yml
  tasks:
    - name: create user ansible
      user:
        name: ansible
        password: "{{ password }}"
