---
- name: install ftp to export repo
  hosts: control
  tasks:
      - name: install FTP server
        package:
            name: vsftpd
            state: latest

      - name: start FTP server
        service:
            name: vsftpd
            state: started
            enabled: yes

      - name: open firewall for FTP
        firewalld:
            service: ftp
            state: enabled
            permanent: yes
            immediate: yes

- name: setup the repo directory
  hosts: control
  tasks:
      - name: make directory
        file:
            path: /var/ftp/repo
            state: directory

      - name: install dnf utils
        package:
            name: 
              - dnf-utils
              - createrepo
            state: latest

      - name: download sample package
        command: yumdownloader nmap --destdir /var/ftp/repo

      - name: createrepo
        command: createrepo /var/ftp/repo
