---
- name: configure repository
  hosts: prod
  vars:
      my_package: nmap
  tasks:
      - name: get package facts
        package_facts:
            manager: auto

      - name: show package facts for my_package
        debug:
            var: ansible_facts.packages[my_package]

      - name: connect to control repo
        yum_repository:
            name: lesson12
            description: RHCE8 lesson 12 repo
            file: lesson12
            baseurl: ftp://rhelc/repo/
            gpgcheck: no

      - name: install package
        package:
            name: "{{ my_package }}"
            state: present
        tags: ['install-pkg']

      - name: update package facts
        package_facts:
            manager: auto

      - name: show package facts for my_package
        debug:
            var: ansible_facts.packages[my_package]
        when: my_package in ansible_facts.packages
