---
- name: The Authorized Key Module
  hosts: rhel01
  become: true
  tasks:
      - name: Set authorized key
        authorized_key:
            user: lupera1
            state: present
            key: "{{ lookup('file', '/home/lupera1/.ssh/id_rsa.pub') }}"
